name: "Update Regions"

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 8 * * *'
  push:

jobs:
    update_regions:

        runs-on: ubuntu-latest

        steps:
          - name: Checkout Repo
            uses: actions/checkout@v2
            with:
               ref: ${{ github.ref }}

          - name: Set up Python
            uses: actions/setup-python@v2
            with: 
              python-version: '3.x'

          - name: Install Geopandas
            run: |
              python -m pip install -U pip
              pip install geopandas
          - name: Install Shapely
            run: |
              python -m pip install -U pip
              pip install shapely
          - name: Install Requests
            run: |
              python -m pip install -U pip
              pip install requests
          - name: Import test
            run: python3 importtest.py
            env:
              AUTH_URL: ${{ secrets.AUTH_URL }}
              ITERATIONS_END: ${{ secrets.ITERATIONS_END }}
            
© 2021 GitHub, Inc.
Terms
Privacy
Security
Status
Doc
